apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name:  database
stringData:
  AUTH_DB: mongodb+srv://<username>:<password>@<cluster-host>/auth-service
  AI_DB: mongodb+srv://<username>:<password>@<cluster-host>/ai-service
  PROJECT_DB: mongodb+srv://<username>:<password>@<cluster-host>/project-service

---

apiVersion: v1
kind: Secret
metadata:
  name: ai
type: Opaque
stringData:
  MISTRAL_API_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX



--- 

apiVersion: v1
kind: Secret
metadata:
  name: auth
type: Opaque
stringData:
  ACCESS_TOKEN_SECRET: <replace-with-a-long-random-value>
  REFRESH_TOKEN_SECRET: <replace-with-a-different-long-random-value>

   

---

apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID:  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


---

apiVersion: v1
kind: Secret
metadata:
  name: redis
type: Opaque
stringData:
  REDIS_URL: redis://redis:6379